dmf:
  features:
    - 0_precipitation
    - 1_precipitation
    - 2_precipitation
    - 3_precipitation
    - 4_precipitation
    - 5_precipitation
    - 6_precipitation
    - 7_precipitation
    - 8_precipitation
    - 9_precipitation
    - 10_precipitation
    - 11_precipitation
    - 12_precipitation
    - 0_temperature
    - 1_temperature
    - 2_temperature
    - 3_temperature
    - 4_temperature
    - 5_temperature
    - 6_temperature
    - 7_temperature
    - 8_temperature
    - 9_temperature
    - 10_temperature
    - 11_temperature
    - 12_temperature
    - 0_relative_humidity
    - 1_relative_humidity
    - 2_relative_humidity
    - 3_relative_humidity
    - 4_relative_humidity
    - 5_relative_humidity
    - 6_relative_humidity
    - 7_relative_humidity
    - 8_relative_humidity
    - 9_relative_humidity
    - 10_relative_humidity
    - 11_relative_humidity
    - 12_relative_humidity
    - 0_price
    - 1_price
    - 2_price
    - 3_price
    - 4_price
    - 5_price
    - 6_price
    - 7_price
    - 8_price
    - 9_price
    - 10_price
    - 11_price
    - 12_price
    - 13_price
    - 14_price
    - 15_price
    - 16_price
    - 17_price
    - 18_price
    - 19_price
    - 20_price
    - 21_price
    - 22_price
    - 23_price
    - 0_load
    - 1_load
    - 2_load
    - 3_load
    - 4_load
    - 5_load
    - 6_load
    - 7_load
    - 8_load
    - 9_load
    - 10_load
    - 11_load
    - 12_load
    - 0_renewable_share_of_load
    - 1_renewable_share_of_load
    - 2_renewable_share_of_load
    - 3_renewable_share_of_load
    - 4_renewable_share_of_load
    - 5_renewable_share_of_load
    - 6_renewable_share_of_load
    - 7_renewable_share_of_load
    - 8_renewable_share_of_load
    - 9_renewable_share_of_load
    - 10_renewable_share_of_load
    - 11_renewable_share_of_load
    - 12_renewable_share_of_load
    - 0_renewable_share_of_generation
    - 1_renewable_share_of_generation
    - 2_renewable_share_of_generation
    - 3_renewable_share_of_generation
    - 4_renewable_share_of_generation
    - 5_renewable_share_of_generation
    - 6_renewable_share_of_generation
    - 7_renewable_share_of_generation
    - 8_renewable_share_of_generation
    - 9_renewable_share_of_generation
    - 10_renewable_share_of_generation
    - 11_renewable_share_of_generation
    - 12_renewable_share_of_generation
    - 0_sum_cbet
    - 1_sum_cbet
    - 2_sum_cbet
    - 3_sum_cbet
    - 4_sum_cbet
    - 5_sum_cbet
    - 6_sum_cbet
    - 7_sum_cbet
    - 8_sum_cbet
    - 9_sum_cbet
    - 10_sum_cbet
    - 11_sum_cbet
    - 12_sum_cbet
    - 0_24_rmean_price
    - 1_24_rmean_price
    - 2_24_rmean_price
    - 3_24_rmean_price
    - 4_24_rmean_price
    - 5_24_rmean_price
    - 6_24_rmean_price
    - 7_24_rmean_price
    - 8_24_rmean_price
    - 9_24_rmean_price
    - 10_24_rmean_price
    - 11_24_rmean_price
    - 12_24_rmean_price
    - 13_24_rmean_price
    - 14_24_rmean_price
    - 15_24_rmean_price
    - 16_24_rmean_price
    - 17_24_rmean_price
    - 18_24_rmean_price
    - 19_24_rmean_price
    - 20_24_rmean_price
    - 21_24_rmean_price
    - 22_24_rmean_price
    - 23_24_rmean_price
    - 0_168_rmean_price
    - 1_168_rmean_price
    - 2_168_rmean_price
    - 3_168_rmean_price
    - 4_168_rmean_price
    - 5_168_rmean_price
    - 6_168_rmean_price
    - 7_168_rmean_price
    - 8_168_rmean_price
    - 9_168_rmean_price
    - 10_168_rmean_price
    - 11_168_rmean_price
    - 12_168_rmean_price
    - 13_168_rmean_price
    - 14_168_rmean_price
    - 15_168_rmean_price
    - 16_168_rmean_price
    - 17_168_rmean_price
    - 18_168_rmean_price
    - 19_168_rmean_price
    - 20_168_rmean_price
    - 21_168_rmean_price
    - 22_168_rmean_price
    - 23_168_rmean_price
    - 0_672_rmean_price
    - 1_672_rmean_price
    - 2_672_rmean_price
    - 3_672_rmean_price
    - 4_672_rmean_price
    - 5_672_rmean_price
    - 6_672_rmean_price
    - 7_672_rmean_price
    - 8_672_rmean_price
    - 9_672_rmean_price
    - 10_672_rmean_price
    - 11_672_rmean_price
    - 12_672_rmean_price
    - 13_672_rmean_price
    - 14_672_rmean_price
    - 15_672_rmean_price
    - 16_672_rmean_price
    - 17_672_rmean_price
    - 18_672_rmean_price
    - 19_672_rmean_price
    - 20_672_rmean_price
    - 21_672_rmean_price
    - 22_672_rmean_price
    - 23_672_rmean_price
    - 0_24_rvar_price
    - 1_24_rvar_price
    - 2_24_rvar_price
    - 3_24_rvar_price
    - 4_24_rvar_price
    - 5_24_rvar_price
    - 6_24_rvar_price
    - 7_24_rvar_price
    - 8_24_rvar_price
    - 9_24_rvar_price
    - 10_24_rvar_price
    - 11_24_rvar_price
    - 12_24_rvar_price
    - 13_24_rvar_price
    - 14_24_rvar_price
    - 15_24_rvar_price
    - 16_24_rvar_price
    - 17_24_rvar_price
    - 18_24_rvar_price
    - 19_24_rvar_price
    - 20_24_rvar_price
    - 21_24_rvar_price
    - 22_24_rvar_price
    - 23_24_rvar_price
    - 0_168_rvar_price
    - 1_168_rvar_price
    - 2_168_rvar_price
    - 3_168_rvar_price
    - 4_168_rvar_price
    - 5_168_rvar_price
    - 6_168_rvar_price
    - 7_168_rvar_price
    - 8_168_rvar_price
    - 9_168_rvar_price
    - 10_168_rvar_price
    - 11_168_rvar_price
    - 12_168_rvar_price
    - 13_168_rvar_price
    - 14_168_rvar_price
    - 15_168_rvar_price
    - 16_168_rvar_price
    - 17_168_rvar_price
    - 18_168_rvar_price
    - 19_168_rvar_price
    - 20_168_rvar_price
    - 21_168_rvar_price
    - 22_168_rvar_price
    - 23_168_rvar_price
    - 0_672_rvar_price
    - 1_672_rvar_price
    - 2_672_rvar_price
    - 3_672_rvar_price
    - 4_672_rvar_price
    - 5_672_rvar_price
    - 6_672_rvar_price
    - 7_672_rvar_price
    - 8_672_rvar_price
    - 9_672_rvar_price
    - 10_672_rvar_price
    - 11_672_rvar_price
    - 12_672_rvar_price
    - 13_672_rvar_price
    - 14_672_rvar_price
    - 15_672_rvar_price
    - 16_672_rvar_price
    - 17_672_rvar_price
    - 18_672_rvar_price
    - 19_672_rvar_price
    - 20_672_rvar_price
    - 21_672_rvar_price
    - 22_672_rvar_price
    - 23_672_rvar_price
  targets:
    - price_0
    - price_1
    - price_2
    - price_3
    - price_4
    - price_5
    - price_6
    - price_7
    - price_8
    - price_9
    - price_10
    - price_11
    - price_12
    - price_13
    - price_14
    - price_15
    - price_16
    - price_17
    - price_18
    - price_19
    - price_20
    - price_21
    - price_22
    - price_23